// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmeewokkpxzkkgraypmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtZWV3b2trcHh6a2tncmF5cG1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MTA1NjUsImV4cCI6MjA1NjQ4NjU2NX0.TKGzpozJGvdbNmYBX24WqB9ogAqxFDgxqEk9py_uOdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);